### ISSUE TITLE
[java] Auxclasspath in PMD CLI does not support relative file path

### ISSUE THREAD

**Issue by Fernal73** [pmd/pmd#2549]
**Affects PMD Version:** 
6.24.0 onwards.

**Description:**

Auxclasspath does not support relative file path when specifying classpath file in PMD CLI namely file URLs with the format
file:./fname

(This could be mitigated by using command realpath to obtain the full path.)

Additionally, the file parameter could be specified in a new option, auxclasspathfile instead.

**Exception Stacktrace:**

```
WARNING: Auxclasspath entry file:/data/data/com.termux/files/home/LearnJava/Unsafe/file doesn't exist, ignoring it
May 28, 2020 3:04:43 AM net.sourceforge.pmd.cache.FileAnalysisCache persist
INFO: Analysis cache updated
./pmdauxrel exited with error code 4
```

**Running PMD through:** *[CLI ]*

**Comment by adangel** [comment]
Yes, that seems to be bug. I looked at the code: the auxclasspath should work (otherwise you would have seen a FileNotFoundException somewhere). The warning message comes from the incremental cache, which calculates the checksum of the auxclasspath - and there we are missing the support for (PMD's own special) file:/ notation.

https://github.com/pmd/pmd/blob/bc4a1d67eb091eeebcad26983eeeafbc68aa2698/pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java#L225

Something weird is going on. Is `file:/data/data/com.termux/files/home/LearnJava/Unsafe/file` the file with the additional paths or is it one of the paths in the file with additional paths? (AbstractAnalysisCache shouldn't see the original text file with the paths anymore, but only the content, so I guess, it's the latter case).

Would you mind to share the file `file:./fname` you used?

I guess, there are two cases to be checked:
* the file URL in the auxclasspath on the CLI can be relative
* the content of the entries in such file can be relative paths

both cases should handled.

**Comment by Fernal73** [comment]
The file referred to was pmdaux.cp as referred to in other bug.
```
$ cat pmdaux.cp
/data/data/com.termux/files/home/LearnJava/lib/junit-4.13.jar
.
```
There's one relative path and one full path in the file.
In the above case, the file is never read when specified as file:./pmdaux.cp to the option auxclasspath.
Wouldn't it be better to read this as @filename with the jars and directories separated by : or ; instead of a line separator?

**Comment by adangel** [comment]
I figured out the problem now: PMD only allows `file://` prefix when declaring auxclasspath as a file - and this prevents us from using a relative path here. I'll change that, so that PMD only checks for `file:` - then you can use `file:pmdaux.cp` - and it is resolved relative to the current working directory.

I'm still puzzling from where the warning `WARNING: Auxclasspath entry file:/data/data/com.termux/files/home/LearnJava/Unsafe/file doesn't exist, ignoring it` comes from, since "...Unsafe/file" is neither on the commandline nor in pmdaux.cp. I assume for now, this warning message is from a intermediate tryout of yours. If you have specified `-auxclasspath file:/data/data/com.termux/files/home/LearnJava/Unsafe/file` - then this warning message is expected, since PMD is looking for `file://` - and this is not starting with that. So it uses this directly as a classpath-entry-url and obviously, the file doesn't exist. The analysis cache wants to read this "jar" file in order to calculate the checksum - so we can detect, if the auxclasspath changes which invalidates the cache.
I think, this issue here is unrelated to the analysis cache, so I'll remove it from the title.

> Wouldn't it be better to read this as @filename with the jars and directories separated by : or ; instead of a line separator?

I'm not sure, I understand exactly, what you want. I assume, with "@filename" you are referring to the java commandline feature [command line argument files](https://docs.oracle.com/en/java/javase/14/docs/specs/man/java.html#java-command-line-argument-files).
I've decided for now against introducing this, but we should consider this as part of PMD 7 CLI.

**Comment by Fernal73** [comment]
I'm still encountering the warning.
You can check out my script pmdauxrel on my repository which reproduces the
said error.
Run it as bash -x ./pmdauxrel Unsafe in the root directory to reproduce the
said warning.

**Comment by Fernal73** [comment]
I look forward to @ file expansions in PMD 7. The argument for it, in this case, is that pmd will no longer have to reconstruct a classpath from the input file and can use its contents as-is.

**Comment by Fernal73** [comment]
From the documentation:

https://pmd.github.io/latest/pmd_userdocs_cli_reference.html#options

-auxclasspath <cp> | Specifies the classpath for libraries used by the source code. This is used to resolve types in source files. Alternatively, a file:// URL to a text file containing path elements on consecutive lines can be specified.
-- | --

**Comment by adangel** [comment]
> I'm still encountering the warning.

Sure you do - this issue will only be fixed with the next PMD version.

**Comment by Fernal73** [comment]
> > I'm still encountering the warning.
> 
> Sure you do - this issue will only be fixed with the next PMD version

That's not what I meant. You asked me to try again; so I did since you implied that the WARNING was non-existent.

> With PMD 6.25.0, we'll see, that the auxclasspath begins with "file:" and load the file "/data/data/com.termux/files/home/LearnJava/Unsafe/compile.cp" and use the contents to construct the URLs for the URLClassLoader (as documented, line by line).

This is what should have been happening. Additionally, my compile.cp (as it currently exists in my repo) does not contain line separators. So I had to create a file that did specifically for this input. A line-separated classpath is not what's expected on the command line and that's my point about using @ expansion. No reconstruction of the classpath is required at all.

**Comment by Fernal73** [comment]
Just a note. Relative file path is accepted for ruleset in the Maven plugin.
